// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi691tPHpccIj3A2cPKX_6Bbbic7gxysY',
    appId: '1:776343065784:web:f0db287fa6d311a866904d',
    messagingSenderId: '776343065784',
    projectId: 'tourist-app-d8352',
    authDomain: 'tourist-app-d8352.firebaseapp.com',
    storageBucket: 'tourist-app-d8352.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA1KTgl-C3Qh2YPLG5mpbO0bHamxjmhtk',
    appId: '1:776343065784:android:9311104822511e1066904d',
    messagingSenderId: '776343065784',
    projectId: 'tourist-app-d8352',
    storageBucket: 'tourist-app-d8352.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5_K1kGvDjZGOYWHAGAjwTm_SwNztr5dI',
    appId: '1:776343065784:ios:3359492a3d9b3f6066904d',
    messagingSenderId: '776343065784',
    projectId: 'tourist-app-d8352',
    storageBucket: 'tourist-app-d8352.firebasestorage.app',
    iosBundleId: 'com.example.touristApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5_K1kGvDjZGOYWHAGAjwTm_SwNztr5dI',
    appId: '1:776343065784:ios:3359492a3d9b3f6066904d',
    messagingSenderId: '776343065784',
    projectId: 'tourist-app-d8352',
    storageBucket: 'tourist-app-d8352.firebasestorage.app',
    iosBundleId: 'com.example.touristApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi691tPHpccIj3A2cPKX_6Bbbic7gxysY',
    appId: '1:776343065784:web:642180890668106566904d',
    messagingSenderId: '776343065784',
    projectId: 'tourist-app-d8352',
    authDomain: 'tourist-app-d8352.firebaseapp.com',
    storageBucket: 'tourist-app-d8352.firebasestorage.app',
  );
}
