name: Flutter CI/CD Pipeline

on:
  push:
    branches:
      - testing-branch
  pull_request:
    branches:
      - testing-branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: flutter/action@v1
      - run: flutter pub get
      - run: flutter build apk
      - uses: actions/upload-artifact@v4
        with: release-apk
        path: build/outputs/apk/release/app-release.apk